"""empty message

Revision ID: 73227eb2fa11
Revises: 
Create Date: 2017-10-08 17:53:37.815542

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils import PasswordType

# revision identifiers, used by Alembic.
revision = '73227eb2fa11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('key', sa.String(length=10), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('login', sa.String(length=80), nullable=True),
                    sa.Column('password',
                              PasswordType(schemes=['pbkdf2_sha512', 'md5_crypt'], deprecated=['md5_crypt']),
                              nullable=True),
                    sa.Column('gender', sa.String(length=80), nullable=True),
                    sa.Column('xp', sa.Integer(), nullable=True),
                    sa.Column('image_big', sa.String(length=120), nullable=True),
                    sa.Column('role', sa.String(length=80), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login')
                    )
    op.create_table('event',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('author_id', sa.Integer(), nullable=True),
                    sa.Column('title', sa.String(length=80), nullable=True),
                    sa.Column('description_short', sa.String(length=80), nullable=True),
                    sa.Column('description', sa.String(length=120), nullable=True),
                    sa.Column('max_participants', sa.Integer(), nullable=True),
                    sa.Column('status', sa.String(length=80), nullable=True),
                    sa.Column('best_player_reward', sa.Integer(), nullable=True),
                    sa.Column('result_file', sa.String(length=120), nullable=True),
                    sa.Column('date_start', sa.DateTime(), nullable=True),
                    sa.Column('image_big', sa.String(length=120), nullable=True),
                    sa.Column('published', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('event_participate',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('event_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
                    )
    op.create_table('event_result',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('event_id', sa.Integer(), nullable=True),
                    sa.Column('place', sa.Integer(), nullable=True),
                    sa.Column('reward', sa.Integer(), nullable=True),
                    sa.Column('rewarded', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('event_wait',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('event_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_wait')
    op.drop_table('event_result')
    op.drop_table('event_participate')
    op.drop_table('event')
    op.drop_table('user')
    op.drop_table('invite')
    # ### end Alembic commands ###
