"""empty message

Revision ID: d0ce82d8f0ed
Revises: 73227eb2fa11
Create Date: 2017-10-09 16:35:39.808865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ce82d8f0ed'
down_revision = '73227eb2fa11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('rewards', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'rewards')
    # ### end Alembic commands ###
